name: deploy
on:
  push:
    branches: [main]
env:
  REACT_APP_API_SERVER: ${{ secrets.REACT_APP_API_SERVER}}
  REACT_APP_GITHUB_CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
  REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
  REACT_APP_GOOGLE_REDIRECT: ${{ secrets.REACT_APP_GOOGLE_REDIRECT }}
  REACT_APP_KAKAO_CLIENT_ID: ${{ secrets.REACT_APP_KAKAO_CLIENT_ID }}
  REACT_APP_KAKAO_REDIRECT: ${{ secrets.REACT_APP_KAKAO_REDIRECT }}
  REACT_APP_TINYMCE_API_KEY: ${{ secrets.REACT_APP_TINYMCE_API_KEY }}
  CI: false

jobs:
  deploy:
    runs-on: ["self-hosted", "Linux", "X64"]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install npm packages
        run: cd frontend && npm ci

      - name: Build
        run: cd frontend && npm run build

      - name: Kill process
        run: fuser -k 3000/tcp || true

      - name: Run server in background
        run: |
          cd frontend
          RUNNER_TRACKING_ID="" nohup serve -s build &

      - name: Delay for server start
        run: sleep 10

      - name: Check if server is running on port 3000
        run: lsof -i :3000
