name: deploy
on:
  push:
    branches: [main]
env:
  REACT_APP_API_SERVER: ${{ secrets.REACT_APP_API_SERVER}}
  REACT_APP_GITHUB_CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
  REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
  REACT_APP_GOOGLE_REDIRECT: ${{ secrets.REACT_APP_GOOGLE_REDIRECT }}
  REACT_APP_KAKAO_CLIENT_ID: ${{ secrets.REACT_APP_KAKAO_CLIENT_ID }}
  REACT_APP_KAKAO_REDIRECT: ${{ secrets.REACT_APP_KAKAO_REDIRECT }}
  REACT_APP_TINYMCE_API_KEY: ${{ secrets.REACT_APP_TINYMCE_API_KEY }}
jobs:
  deploy:
    runs-on: ["self-hosted", "Linux", "X64"]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: cd frontend
        run: cd frontend
      - name: Install npm packages
        run: npm ci
      - name: Build
        run: NODE_OPTIONS="--max_old_space_size=8192" npm run build
      - name: Kill process
        run: fuser -k 3000/tcp
      - name: Run background
        run: RUNNER_TRACKING_ID="" && nohup serve -s build &
