name: deploy
on:
  push:
    branches: [main]
env:
  REACT_APP_API_SERVER: ${{ secrets.REACT_APP_API_SERVER}}
  REACT_APP_GITHUB_CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
  REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
  REACT_APP_GOOGLE_REDIRECT: ${{ secrets.REACT_APP_GOOGLE_REDIRECT }}
  REACT_APP_KAKAO_CLIENT_ID: ${{ secrets.REACT_APP_KAKAO_CLIENT_ID }}
  REACT_APP_KAKAO_REDIRECT: ${{ secrets.REACT_APP_KAKAO_REDIRECT }}
  REACT_APP_TINYMCE_API_KEY: ${{ secrets.REACT_APP_TINYMCE_API_KEY }}
  CI: false

jobs:
  deploy:
    runs-on: ["self-hosted", "Linux", "X64"]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install npm packages
        run: cd frontend && npm ci

      - name: Build
        run: cd frontend && npm run build

      - name: Stop existing PM2 process
        run: pm2 delete my-app || true

      - name: Start PM2 process on port 3000
        run: pm2 start ecosystem.config.js

      - name: Delay for server start
        run: sleep 10

      - name: Show PM2 Logs
        run: pm2 logs my-app

      - name: Check PM2 Process Status
        run: pm2 status

      - name: Verify Port Listening
        run: lsof -i :3000
